### PR TITLE
Show and remove deprecation warnings in tests

### PR DESCRIPTION
**Pull request by meshy**

### CODE REVIEW

**Comment by meshy** [comment]
Blocked by #44

**Comment by KevinEtienne** [comment]
It looks like there're 3 other warnings (2 for `django 1.9` and 1 for `django 1.10`:

```bash
/home/travis/build/meshy/django-conman/conman/redirects/handlers.py:7: RemovedInDjango19Warning: Default value of 'RedirectView.permanent' will change from True to False in Django 1.9. Set an explicit value to silence this warning.

  view = views.RouteRedirectView.as_view()
```

```bash
/home/travis/build/meshy/django-conman/conman/redirects/tests/test_handlers.py:17: RemovedInDjango19Warning: Default value of 'RedirectView.permanent' will change from True to False in Django 1.9. Set an explicit value to silence this warning.

  expected = RouteRedirectView.as_view()
```

```bash
/home/travis/build/meshy/django-conman/conman/routes/tests/urls.py:12: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got conman.routes.tests.urls.dummy_view). Pass the callable instead.

  url(r'^$', view_path),
```

**Comment by meshy** [comment]
Yeah, I wasn't quite sure how to deal with those.

The first two relate to the fact that [RouteRedirectView](https://github.com/meshy/django-conman/blob/b6d7754d90a5f55961f9e3ac37ecaf1a2bf508e4/conman/redirects/views.py#L4-L14) does not explicitly set `permanent`. As it's set dynamically, I'm not sure what to do.

I could add `permanent = None`, I suppose, but that seems wrong somehow, as it will be overridden.

I could make it a property, and move the logic out of the `get_redirect_url` method (as this also seems a little wrong to me).

Alternatively, I could just use a function-based view `;)` -- It would be even simpler than it currently is, but wouldn't be extensible. Perhaps the question is: how extensible does this need to be?

**Comment by meshy** [comment]
The third warning is a bit harder -- the whole file only exists as a test, but if I replace [the path](https://github.com/meshy/django-conman/blob/ef1c03f9034ac57738bd91194e4bbca5ff28a41d/conman/routes/tests/urls.py#L8) with the callable function, then I need to [find a new way to override it](https://github.com/meshy/django-conman/blob/76173f4866b90d8932f7f86be478871172bfc7b1/conman/routes/tests/test_handlers.py#L46).

**Comment by meshy** [comment]
Perhaps we just need to run [`clear_url_caches`](https://github.com/meshy/django-conman/blob/76173f4866b90d8932f7f86be478871172bfc7b1/conman/routes/tests/test_handlers.py#L50) in the `setUp`...

**Comment by Ian-Foote** [comment]
I think I would set `permanent=False` to the `RouteRedirectView`. This will silence the warning by opting in to the default future behaviour. It doesn't really matter that we always explicitly override it later.

**Comment by meshy** [comment]
> I think I would set `permanent=False` to the `RouteRedirectView`.

Seems quite 
reasonable.

**Comment by KevinEtienne** [comment]
Oh I see! Except using a function which would return a string, I'm not sure what could be used

**Comment by meshy** [comment]
@KevinEtienne @Ian-Foote I think it might be best to deal with the other warnings in another PR -- you happy with what's here?

**Comment by Ian-Foote** [comment]
Nothing looks wrong on a quick scan.

**Comment by KevinEtienne** [comment]
Looks good to me

**Comment by meshy** [comment]
Ta!

**Pull request merged**
