### PR TITLE
Simplify Route.slug.help_text

### LINKED ISSUE #48: Fix help_text indentation of Route.slug
See https://github.com/meshy/django-conman/pull/44/files#r35869309.

This probably wants to be reduced to a single line of text, as that's how it's displayed in the admin anyway.

### PR DESCRIPTION
**Pull request by Ian-Foote**
Fix #48 and #49.

### CODE REVIEW

**Comment by meshy** [comment]
:+1:

**Comment by meshy** [comment]
:cake:

**Comment by meshy** [comment]
Thank you!

**Comment by meshy** [comment]
Oops! This needed a migration!

**Comment by Ian-Foote** [comment]
Oops. Do you want to do that or shall I?

**Pull request merged**
